name: Update README

on:
  schedule:
    - cron: '*/24 * * * *'
  workflow_dispatch:

  push:
    branches:
    - master
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
